  CREATE TABLE "BOARD_COMMENT" (	
  	"BOARD_ID" NUMBER NOT NULL ENABLE, 
	"COMMENT_ID" NUMBER NOT NULL ENABLE, 
	"COMMENT_CONTENT" VARCHAR2(1000 BYTE), 
	"COMMENT_REG_DT" DATE DEFAULT SYSDATE, 
	"COMMENT_LUP_DT" DATE DEFAULT SYSDATE, 
	"USER_ID" VARCHAR2(100 BYTE), 
	 CONSTRAINT "BOARD_COMMENT_PK" PRIMARY KEY ("BOARD_ID", "COMMENT_ID")
 )