CREATE TABLE "HEALTH" (	
	"USER_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"HEALTH_YYYY" NUMBER NOT NULL ENABLE, 
	"HEALTH_MM" NUMBER NOT NULL ENABLE, 
	"HEALTH_DD" NUMBER NOT NULL ENABLE, 
	"HEALTH_DISTANCE" NUMBER, 
	"HEALTH_TIME" NUMBER, 
	"HEALTH_SPEED" NUMBER(*,2), 
	"HEALTH_CALORIES" NUMBER(*,2), 
	CONSTRAINT "HEALTH_PK" PRIMARY KEY ("USER_ID", "HEALTH_YYYY", "HEALTH_MM", "HEALTH_DD")
)